### PR TITLE
add group 4 week 4 discussion notes

### PR DESCRIPTION
**Pull request by caifand**
Thanks for facilitating the enjoyable discussion!

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by alexcasper** [comment]
Thanks for taking notes Fan!

**Comment by tobyhodges** [comment]
Thanks both 👍

**Review by tobyhodges — CHANGES_REQUESTED** [review]
@caifand this was week 5 of the program - please rename the file to move it to the `week5` directory. I guess we are missing the notes from week 4 for this group and some others? I will reach out to the other notetakers...

**Comment by caifand** [comment]
> @caifand this was week 5 of the program - please rename the file to move it to the `week5` directory. I guess we are missing the notes from week 4 for this group and some others? I will reach out to the other notetakers...

Thanks for checking them. I added the missing one to week4/ and moved this one to week5/. See if they are ok now? Thanks @tobyhodges

**Review by tobyhodges — APPROVED** [review]
Thank you @caifand!

**Pull request merged**
